services:
  rust-dev:
    image: rust:latest
    container_name: airis-mock
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    ports:
      - 4567:4567
    command: cargo run
    networks:
      - default
