openapi: 3.0.3
info:
  title: AIRIS Mock Service
  version: 0.1.0
  description: |-
    This is [AIRIS](https://airia.or.jp/airis/index.html) mocking service.
    it has only `UniqueSearchServlet`.
    vehicle shape code master is from [Ministry of Land, Infrastructure, Transport and Tourism](https://www.kodokensaku.mlit.go.jp/motas/topPage).
    [車体の形状コード表](https://www.kodokensaku.mlit.go.jp/motas/resource/1700179039000/OtherCode/OtherCode/02.csv)
servers:
  - url: http://localhost:4567
paths:
  /:
    get:
      summary: get random Body Type
      responses:
        200:
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/BodyType"
  /body-types:
    get:
      summary: get Body Type List
      responses:
        200:
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/ShapeCodeList"
  /health-check:
    get:
      summary: health check
      responses:
        200:
          description: Successful operation
          content:
            text/html:
              schema:
                type: string
  /teikyou/check:
    post:
      summary: check teikyou unique search servlet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TeikyouUniqueSearchServlet"
      responses:
        200:
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/TeikyouUniqueSearchServlet"
        422:
          description: Validation exception
  /teikyou/UniqueSearchServlet:
    post:
      summary: teikyou unique search servlet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TeikyouUniqueSearchServlet"
      responses:
        200:
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/AirisResponseBody"
        422:
          description: Validation exception

components:
  schemas:
    BodyType:
      type: object
      properties:
        NAME:
          type: string
          example: ボンネット
        CD:
          type: string
          example: 1001
      xml:
        name: BODYTYPE
    ShapeCode:
      type: object
      properties:
        classification:
          type: string
          nullable: true
          example: 貨物自動車
        purpose:
          type: string
          nullable: true
          example: 貨物用
        code:
          type: string
          example: 11
        body_type:
          type: string
          example: ボンネット
        remarks:
          type: string
          nullable: true
          example: null
      xml:
        name: ShapeCode
    TeikyouUniqueSearchServlet:
      type: object
      properties:
        searchdate:
          type: string
          example: 20250126
        searchid:
          type: string
          example: 02
        privacyflg:
          type: integer
          example: 0
        seqno:
          type: integer
          example: 1
        retryflg:
          type: integer
          example: 0
        groupid:
          type: string
          example: 01
        regno:
          type: string
          example: 品川０１２あ１２３４
        chassisno:
          type: string
          example: ABCD-1234
        version:
          type: string
          example: 1.0
        userid:
          type: string
          example: userid001
        pw:
          type: string
          example: password001
        keyword:
          type: string
          example: keyword001
      xml:
        name: TeikyouUniqueSearchServletResponse
    AirisResponseBody:
      type: object
      properties:
        COMMON:
          $ref: "#/components/schemas/AirisCommon"
        DATA:
          $ref: "#/components/schemas/AirisData"
        ERRINFO:
          $ref: "#/components/schemas/AirisErrInfo"
      xml:
        name: RESPONSE
    AirisCommon:
      type: object
      properties:
        ORGNAME:
          type: string
          example: 品川
        VERSION:
          type: string
          example: 1.0
        SEARCHDATE:
          type: string
          example: 20250126
        SEARCHID:
          type: string
          example: 02
        SEQNO:
          type: integer
          example: 1
        RESULT:
          type: integer
          example: 0
        NUM:
          type: integer
          example: 1
      xml:
        name: COMMON
    AirisData:
      type: object
      properties:
        REGDATE:
          type: string
          example: 20240126
        FIRSTREGDATE:
          type: string
          example: 20240126
        PURPOSE:
          type: string
          example: 1
        BODYTYPE:
          $ref: "#/components/schemas/BodyType"
        LOADAGE:
          $ref: "#/components/schemas/LoadAgeType"
        WEIGHT:
          $ref: "#/components/schemas/WeightType"
        GROSSWEIGHT:
          $ref: "#/components/schemas/GrossWeightType"
        EXPIRYDATE:
          type: string
          example: 20260126
        CARID:
          type: string
          example: ABCD-1234
        ELECTRO_CARINS:
          type: string
          example: 1
      xml:
        name: DATA
    AirisErrInfo:
      type: object
      properties:
        ERRID:
          type: string
          example: 0001
        ERRMSG:
          type: string
          example: エラーが発生しました
      xml:
        name: ERRINFO
    LoadAgeType:
      type: object
      properties:
        VALUE_1:
          type: integer
          example: 4000
        VALUE_2:
          type: integer
          example: 3000
      xml:
        name: LOADAGE
    WeightType:
      type: object
      properties:
        VALUE:
          type: integer
          example: 4000
      xml:
        name: WEIGHT
    GrossWeightType:
      type: object
      properties:
        VALUE_1:
          type: integer
          example: 4000
        VALUE_2:
          type: integer
          example: 3000
      xml:
        name: GROSSWEIGHT
    ShapeCodeList:
      type: object
      properties:
        shape_codes:
          type: array
          items:
            $ref: "#/components/schemas/ShapeCode"
